### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by hoijui** [livibetter/x#1]
hey! :-)
saw this rep of yours, and i read the README, but to me it is not clear why i would want to use `x xeyes` instead of just `xeyes`. could you maybe explain?

**Comment by livibetter** [comment]
Try:

```
$ firefox
```

That should be enough of reason as you can see a ton of message being printed out for your debugging purpose, and you can't use the shell until the process ends.  Actually, you can, you just need to put it in background, but you wouldn't want to do it every time.  This is why I wrote `x`.

The `x` is a helper, just one line actually:

```bash
nohup "$@" &> /dev/null &
```

That is the entire source code.  (I watered it down with lots of comments)

You make me believe not many people have never practically use shell as launcher, if they do, they will find they need more terminal windows/panes, as shells are all occupied, and pretending all those messages being dumped out are not there to annoy them.

Even so, I still don't plan to expand the `WHY?` section to explain.

Please close the issue if you don't have any further questions or discussions to make.

**Comment by hoijui** [comment]
its not that i don't know any problems like the ones you described, about starting X software from a terminal, but that if you don't explain what problems are solved by your code, i see no use in it, and won't use it.

**Comment by livibetter** [comment]
@hoijui You've convinced me, I have edited in e2faaf6, hopefully that would clarify for people don't take a peek of the code, which mostly wouldn't that, even few might do, it's best to lay it out clearly, that's what this question really is about, I supposed.

I was too lazy to explain, thought it'd be obvious and only considering *why from the terminal* needed an explanation.  Thanks for the nudge!

**Comment by livibetter** [comment]
I've renamed the repo to "Shell is the New Launcher," that's what this repo was supposed to do, to sell the idea, so to speak, not to sell the `x`.

When I got the idea of using the shell/terminal as launcher a year ago, that's like an eureka moment, but I lost sight when I decided to create a repo and making a simple Bash function into a one-liner script, because it's easier to install

When I read your words:

> i see no use in it, and won't use it.

I didn't care, that's why I said I wouldn't expand `WHY?`, because I never had thought that anyone but me would actually `make install` after `git clone`, after all, it's just one single line, and that's why I used `UNLICENSE`, so anyone could just copy and paste.

The whole purpose of the repo is that `WHY?`, I wanted to convey my idea for people who have similar environment, redirecting their thoughts to what a launcher they are looking for.  For me, I don't need a launcher, a shell would do wonderful, but shell wouldn't work for anyone if it's using more conventional DE or non-tilting WM.

I shouldn't have put `x` under the spotlight in the first place, there was no mentions about the idea from your question, that telling me I've failed to tell the idea, whether I could put the idea in your mind, is it good or bad idea for you, that doesn't matter, because you didn't see I was trying to tell the idea, but the `x`, because I didn't try to in the original `README`.

I've reshaped and renamed the repo and rewrote the `README`.

**Comment by hoijui** [comment]
boooaahhh!
it is perfect now, thank you a lot! :-)
and thanks for sharing your though process, too.
it is funny how we can have so many thoughs, write so many words, about a single line of code. but it makes a lot of sense.. it is like philosophy, and self reflection and thus.. meditation, psychology, and when interaction with others sparks from it, like in our case, it becomes a sociological issue too. ;-)
for me, at times when i am disconnected from theworld, deep into code, forgetting too much about the real world out there, something in me still takes note, and that something steers me towards sharing .. whatever.. be it coding, or my code, with other humans. sure, it is a meager way of interaction, but it shows the intention, the desire. yet, until there is feedback, the desire to share is just that, a desire, a hand reaching out into the dark of the night.

as itis now, it is real free software, perfectly explained, and really usefull!
i never had the idea to use/make such a launcher. with this explanation, it now seems like a no-brainer. also, even though i use the shell a lot since years, i did not know about nohup. ;-)
i have `x` in my path now.

nice to see reflection, as you describe it so well, in an other being.
ride on, my friend, ride on!
